### ISSUE TITLE
Tom's suggestions

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/hpoannotqc#6]
https://gist.github.com/TomConlin/5131ad256b6750cbaf5b1bc07538a7fe
thanks to Tom @TomConlin for this. I am answering in comments.

**Comment by pnrobinson** [comment]
Column names for small file
current proposal
```
1:#DiseaseID
2:DiseaseName
3:HpoId
4:HpoName
5:ageOfOnsetId
6:ageOfOnsetName
7:evidenceCode
8:frequencyModifier
9:sex
10:negation
11:modifier
12:description
13:publication
14:assignedBy
15:dateCreated
```
Two suggestions, I think. 
1. Use consistent capitalization. Let's use Camel Case with an initial capital letter
2. Let's not have more than two words (e.g., ageOfOnsetId should be OnsetId)

**Comment by pnrobinson** [comment]
Double semicolons, e.g.,
cut -f2 v2.tab | sort -u | grep -c  ";;" 
2442
* This seems to be coming from the way we have parsed the OMIM synonyms. I will add code to replace double semicolons with a single semicolon in the v2 files.
* Here is an example:
```
#616719 SPINOCEREBELLAR ATAXIA, AUTOSOMAL RECESSIVE 21; SCAR21;;SPINOCEREBELLAR ATAXIA, AUTOSOMAL RECESSIVE 21, WITH HEPATOPATHY
```

**Comment by pnrobinson** [comment]
```
# phenotype_frequency  
# sparse hodgpodge of:
#   nothing 
#	identifiers
#	rationals
# pointlessly precise percentages (including ranges of percentages)
```
There are three allowed formats for frequency. This is messy but it seems to be the best solution so far. See 
```
frequency. This column can be one of three formats: A valid HPO term from the frequency subontology, a fractional expression m/n (e.g., 4/7 meaning that 4 of 7 individuals in the cited study had the disease and the feature in question, while the feature was ruled out in the remaining 3 of 7 individuals); or a percentage value such as 47%. This column may be empty.
```
from http://hpo-annotation-qc.readthedocs.io/en/latest/smallfile.html#current-small-file-format

**Comment by drseb** [comment]
> This seems to be coming from the way we have parsed the OMIM synonyms. I will add code to replace double semicolons with a single semicolon in the v2 files.

No. These are there on purpose.

**Comment by pnrobinson** [comment]
# are all rationals proper?
cut -f8 v2.tab | awk -F'/' '$2>0{if($1>$2)print}'
18/2
# of course not,  that would be silly!
THis is
OMIM-216550.tab:OMIM:216550	COHEN SYNDROME					HP:0000662	Nyctalopia			PCS	PCS	18/2	
thanks for picking this up

**Comment by pnrobinson** [comment]
@drseb We can leave the semicolons as is, but what is their purpose?

**Comment by drseb** [comment]
These are two names for the entries:

- SPINOCEREBELLAR ATAXIA, AUTOSOMAL RECESSIVE 21; SCAR21
- SPINOCEREBELLAR ATAXIA, AUTOSOMAL RECESSIVE 21, WITH HEPATOPATHY

compare with: https://www.omim.org/entry/616719

**Comment by pnrobinson** [comment]
Publications.
There are some entries like this ``PMID:17918734;pmid:12687501```
We should standardize on PMID.
The other oddities are intentional, please see docu page

**Comment by pnrobinson** [comment]
@drseb, still don't understand why we need to have two semicolons in a row. 
My interpretation is that 
SPINOCEREBELLAR ATAXIA, AUTOSOMAL RECESSIVE 21: preferred name
SCAR21: prefered abbreviation
SPINOCEREBELLAR ATAXIA, AUTOSOMAL RECESSIVE 21, WITH HEPATOPATHY: synonym.
Are we using the ';;' as a signal of something then?

**Comment by drseb** [comment]
Yes, this is take from omim. <title>;<abbr>;;<nexttitle>;<nextabbr>;;...

abbr is optional

**Comment by TomConlin** [comment]
they appeared to me to be on purpose because single semicolons are 
already being used in that field


     ... nice weather eh?          tomc@cs.uoregon.edu

**Comment by pnrobinson** [comment]
Let's leave the ;; for now, since we can move to using the Mondo name in a version of the big file if we want to.

**Comment by pnrobinson** [comment]
The date issue is coming from this Apr 3, 0017	
```
OMIM:107850	107850 ARM FOLDING PREFERENCE					HP:0010982	Polygenic inheritance			IEA	IEA						OMIM-CS:INHERITANCE > NON-MENDELIAN, ? HERITABILITY	OMIM:107850	HPO:skoehler	Apr 3, 0017	
```
I just fixed this by hand to 2017-04-03

**Comment by pnrobinson** [comment]
@TomConlin  I cannot find the file with the date "2018-15-20"
```
$ grep '2018-15-20' *.tab
```
gives no result. I am also not sure how to run the script you showed -- please advise!

**Comment by TomConlin** [comment]
@pnrobinson  

works for me, perhaps someone already fixed it the data you are polling

  
grep -l '2018-15-20' *.tab
OMIM-115310.tab
OMIM-147891.tab
OMIM-158901.tab
OMIM-159001.tab
OMIM-212140.tab
OMIM-215150.tab
OMIM-254130.tab
OMIM-300514.tab
OMIM-300523.tab
OMIM-305390.tab
OMIM-600175.tab
OMIM-605373.tab
OMIM-605407.tab
OMIM-613080.tab
OMIM-616517.tab

the git version I am  working against is:


 git log
commit 312b909e61b5038c580deff87117dff489186065
Author: pnrobinson <peter.robinson@jax.org>
Date:   Mon Mar 5 12:21:42 2018 -0500

    Updating annotation files

commit a2632a32b3dfa50c38765579e336a34f82019e92
Author: pnrobinson <peter.robinson@charite.de>
Date:   Sun Mar 4 08:36:13 2018 -0500

    updating annotations

commit a358b7af553ad3637d3e282173fca2f2eaea5d23
Author: pnrobinson <peter.robinson@jax.org>
Date:   Wed Feb 28 14:57:32 2018 -0500

    Updating annotation files

commit 30102e14bc2652d597c2948fe755130b5b533ce1
Author: pnrobinson <peter.robinson@jax.org>
Date:   Wed Feb 28 14:56:20 2018 -0500

    Log file for old file conversion

...

**Comment by pnrobinson** [comment]
I have a slightly newer version, but I did not fix this so thanks to the invisible helping hand!
```
$ grep -l '2018-15-20' *.tab
[~/GIT/hpo-annotation-data/rare-diseases/annotated] $ git log
commit a2f096c8394668726e66ec04813d5c27e354bfb1
Author: pnrobinson <peter.robinson@charite.de>
Date:   Wed Mar 7 17:28:23 2018 -0500

    Adding omit list

commit 5ae1b024085ef0abcbac701af36630c341d8588f
Author: pnrobinson <peter.robinson@charite.de>
Date:   Wed Mar 7 11:00:17 2018 -0500

    Updating annotation
```

**Comment by pnrobinson** [comment]
I updated the 18/2 (it was supposed to be 18/22.

**Comment by pnrobinson** [comment]
I have fixed everything that Tom picked up. Except we decided not the worry about the ";;" for now. And I made a separate issue to standardize on PMID vs pmid. thanks Tom!

**Comment by TomConlin** [comment]
noting that I still see the impossible date  after  a git pull

```
git pull
remote: Counting objects: 106, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 106 (delta 79), reused 103 (delta 76), pack-reused 0
Receiving objects: 100% (106/106), 194.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (79/79), completed with 16 local objects.
From github.com:monarch-initiative/hpo-annotation-data
   312b909..dc1b942  v2files    -> origin/v2files
Updating 312b909..dc1b942
Fast-forward
 ...
```

```
tomc@nada ~/Projects/Monarch/hpo-annotation-data/rare-diseases/annotated/v2files $ git log
commit dc1b942d5d364b05ec53356051126fac85ab1fec
Author: pnrobinson <peter.robinson@charite.de>
Date:   Wed Mar 7 17:56:45 2018 -0500

    correcting malformed frequency in Cohen syndrome

commit a2f096c8394668726e66ec04813d5c27e354bfb1

```

```
grep -l '2018-15-20' *.tab
OMIM-115310.tab
OMIM-147891.tab
OMIM-158901.tab
OMIM-159001.tab
OMIM-212140.tab
OMIM-215150.tab
OMIM-254130.tab
OMIM-300514.tab
OMIM-300523.tab
OMIM-305390.tab
OMIM-600175.tab
OMIM-605373.tab
OMIM-605407.tab
OMIM-613080.tab
OMIM-616517.tab
```

**Comment by pnrobinson** [comment]
strange. Looking into these files I do not find that date, but some of the date fields are empty. I will correct this manually.

**Comment by pnrobinson** [comment]
In fact all of these entries had missing (empty) data fields for some or most of the rows. For some reason that must have been causing the error with the impossible date format.  I added the date to the empty fields with PhenoteFX, and I hope we are now OK.
